# build stage
FROM node:lts-alpine as build-stage

ENV JQ_VERSION=1.6
RUN wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 -O /tmp/jq-linux64
RUN cp /tmp/jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq

WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache bash gettext ca-certificates && \
    npm install

COPY ./start-nginx.sh /usr/bin/start-nginx.sh
COPY . .
RUN chmod +x /usr/bin/start-nginx.sh && \
    jq 'to_entries | map_values({ (.key) : ("$" + .key) }) | reduce .[] as $item ({}; . + $item)' ./src/config.json > ./src/config.tmp.json && \
    mv ./src/config.tmp.json ./src/config.json

ENV JSFOLDER=/app/src/*.json
ENTRYPOINT [ "start-nginx.sh" ]
CMD ["dev"]
