apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: ouistity
build:
  artifacts:
    - image: shokohsc/ouistity
      context: .
      sync:
        manual:
          - src: src/**/*.js
            dest: .
          - src: src/**/*.vue
            dest: .
      docker:
        dockerfile: Dockerfile.dev
manifests:
  kustomize:
    paths:
      - k8s/base
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: shokohsc/ouistity
          sync:
            manual:
              - src: src/**/*.js
                dest: .
              - src: src/**/*.vue
                dest: .
  - name: shokohsc
    build:
      artifacts:
        - image: shokohsc/ouistity
          sync:
            manual:
              - src: src/**/*.js
                dest: .
              - src: src/**/*.vue
                dest: .
          kaniko:
            useNewRun: true
            cache:
              repo: shokohsc/ouistity
            dockerfile: Dockerfile.dev
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
    manifests:
      kustomize:
        paths:
          - k8s/overlays/shokohsc
    deploy:
      kubectl: {}
  - name: prod
    build:
      artifacts:
        - image: shokohsc/ouistity
          kaniko:
            useNewRun: true
            cache:
              repo: shokohsc/ouistity
            dockerfile: Dockerfile
            buildArgs:
              POD_NAME: '{{.GIT_COMMIT}}'
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi